### PR TITLE
Add complete stub code

### PR DESCRIPTION
**Pull request by hsorby**
Add the implementation for a version and versionString with associated tests.

### CODE REVIEW

**Comment by mirams** [comment]
Looks good to me.

**Comment by nickerso** [comment]
@mirams you probably want to check cellml/libcellml :) this is a repo for testing some of the buildbot integration. @hsorby do we still need to keep this one going or should we remove this repository to avoid future confusion? or perhaps rename it something more clearly indicative of its purpose?

**Comment by mirams** [comment]
Oh I see!

**Comment by hsorby** [comment]
I would like to keep it @nickerso for when I need to test Buildbot related issues, I don't have the access (and I'm not asking for it) on cellml/libcellml to do what I need.  I think a rename is best with an informative description.  The code here will be hard to distinguish from cellml/libcellml so we should be very clear about this repositories purpose.

**Pull request closed without merging**
